document.getElementById('year').textContent=new Date().getFullYear();
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
const lb=document.querySelector('.lightbox');const lbImg=lb.querySelector('img');
document.querySelectorAll('.photo').forEach(p=>p.addEventListener('click',()=>{lbImg.src=p.dataset.img;lb.classList.add('open');lb.setAttribute('aria-hidden','false')}));
lb.querySelector('button').addEventListener('click',()=>{lb.classList.remove('open');lb.setAttribute('aria-hidden','true')});
lb.addEventListener('click',e=>{if(e.target===lb)lb.querySelector('button').click()});
